# Generated by Django 4.2.2 on 2023-07-28 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_problem', models.CharField(max_length=300)),
                ('problem_subject', models.CharField(choices=[('Riyaziyyat', 'Riyaziyyat'), ('Kimya', 'Kimya'), ('Fizika', 'Fizika'), ('Biologiya', 'Biologiya'), ('Coğrafiya', 'Coğrafiya'), ('Tarix', 'Tarix'), ('Azərbaycan dili', 'Azərbaycan dili')], max_length=200)),
                ('problem_context_img', models.ImageField(blank=True, null=True, upload_to='problems/')),
                ('problem_context_aze', models.CharField(blank=True, max_length=10000)),
                ('problem_context_eng', models.CharField(blank=True, max_length=10000)),
                ('problem_context_rus', models.CharField(blank=True, max_length=10000)),
                ('problem_views', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('show_problem', models.BooleanField(default=True)),
                ('have_solution', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_path_img', models.ImageField(blank=True, upload_to='solutions/')),
                ('solution_path_video', models.FileField(blank=True, upload_to='solutions/')),
                ('person_solved', models.CharField(max_length=500)),
                ('problem_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problems')),
            ],
        ),
    ]
