# Generated by Django 4.2.2 on 2023-08-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='problem_subject',
            field=models.CharField(max_length=200),
        ),
    ]
