# Generated by Django 4.2.2 on 2023-08-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_problems_problem_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='problem_nth',
            field=models.IntegerField(default=0),
        ),
    ]
