# Generated by Django 4.2.2 on 2023-08-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problems_problem_nth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='problem_nth',
            field=models.IntegerField(),
        ),
    ]
