# Generated by Django 4.2.2 on 2023-08-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_alter_problems_problem_nth'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='user_added',
            field=models.CharField(default='', max_length=600),
        ),
    ]
