# Generated by Django 4.2.3 on 2023-08-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_problems_user_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=800)),
                ('problem_id', models.IntegerField()),
                ('user_added', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='reportedProblems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_report', models.CharField(max_length=1000)),
                ('problem_reported', models.CharField(max_length=1000)),
                ('solution_reported', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='problems',
            name='problem_subject',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='problems',
            name='user_added',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='solutions',
            name='person_solved',
            field=models.CharField(max_length=10000),
        ),
    ]
