# Generated by Django 4.2.3 on 2023-08-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_chat_reportedproblems_alter_problems_problem_subject_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.AlterField(
            model_name='problems',
            name='show_problem',
            field=models.BooleanField(default=False),
        ),
    ]
