# Generated by Django 4.2.2 on 2023-08-15 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_accounts_tag'),
        ('problems', '0009_alter_chat_user_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='user_added',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.accounts'),
        ),
    ]
