# Generated by Django 4.2.3 on 2023-08-17 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0012_alter_chat_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solutions',
            old_name='person_solved',
            new_name='user_solved',
        ),
    ]
