# Generated by Django 4.2.3 on 2023-08-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0013_rename_person_solved_solutions_user_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions',
            name='solution_cont',
            field=models.CharField(default='', max_length=200000),
        ),
    ]
