# Generated by Django 4.2.3 on 2023-08-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0014_solutions_solution_cont'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problems',
            old_name='problem_context_aze',
            new_name='problem_context',
        ),
        migrations.RemoveField(
            model_name='problems',
            name='problem_context_eng',
        ),
        migrations.RemoveField(
            model_name='problems',
            name='problem_context_rus',
        ),
    ]
