# Generated by Django 4.2.3 on 2023-08-18 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0015_rename_problem_context_aze_problems_problem_context_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solutions',
            old_name='problem_name',
            new_name='problem_id',
        ),
    ]
