# Generated by Django 4.2.3 on 2023-08-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0016_rename_problem_name_solutions_problem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='problem_id',
            field=models.IntegerField(),
        ),
    ]
