# Generated by Django 4.2.3 on 2023-08-19 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0017_alter_solutions_problem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='problem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problems'),
        ),
    ]
