# Generated by Django 4.2.3 on 2023-08-19 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0018_alter_solutions_problem_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solutions',
            old_name='problem_id',
            new_name='problem',
        ),
    ]
