# Generated by Django 4.2.3 on 2023-08-19 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_accounts_solve_count'),
        ('problems', '0019_rename_problem_id_solutions_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='user_added',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.accounts'),
        ),
        migrations.AlterField(
            model_name='solutions',
            name='user_solved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.accounts'),
        ),
    ]
