# Generated by Django 4.2.3 on 2023-08-23 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_accounts_account_and_more'),
        ('problems', '0020_alter_problems_user_added_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Problems',
            new_name='Problem',
        ),
        migrations.RenameModel(
            old_name='reportedProblems',
            new_name='ReportedProblem',
        ),
        migrations.RenameModel(
            old_name='Solutions',
            new_name='Solution',
        ),
    ]
