# Generated by Django 4.2.3 on 2023-08-23 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0021_rename_problems_problem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportedproblem',
            name='solution_reported',
        ),
        migrations.AlterField(
            model_name='reportedproblem',
            name='problem_reported',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem'),
        ),
        migrations.AlterField(
            model_name='reportedproblem',
            name='reason_report',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
