# Generated by Django 4.2.3 on 2023-08-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0022_remove_reportedproblem_solution_reported_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportedproblem',
            old_name='reason_report',
            new_name='other',
        ),
        migrations.AddField(
            model_name='reportedproblem',
            name='checkbox_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportedproblem',
            name='checkbox_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportedproblem',
            name='checkbox_problem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportedproblem',
            name='checkbox_solution',
            field=models.BooleanField(default=False),
        ),
    ]
