# Generated by Django 4.2.2 on 2023-09-02 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0023_rename_reason_report_reportedproblem_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
