# Generated by Django 4.2.3 on 2023-09-13 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0024_solution_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='problem_nth',
        ),
    ]
