# Generated by Django 4.2.3 on 2023-09-16 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0025_remove_problem_problem_nth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='problem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem'),
        ),
    ]
