# Generated by Django 4.2.2 on 2023-09-20 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0026_alter_chat_problem_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='problem_id',
            new_name='problem',
        ),
    ]
