# Generated by Django 4.2.3 on 2023-10-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0027_rename_problem_id_chat_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='solution_cont',
            field=models.CharField(blank=True, max_length=200000),
        ),
    ]
