# Generated by Django 5.0 on 2024-01-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0028_alter_solution_solution_cont'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
