# Generated by Django 4.2.2 on 2023-08-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='profile_photo',
            field=models.ImageField(default='default_pp.png', upload_to='profile_photos/'),
        ),
    ]
