# Generated by Django 4.2.3 on 2023-08-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_accounts_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='tag',
            field=models.CharField(default='User', max_length=20),
        ),
    ]
