# Generated by Django 4.2.3 on 2023-08-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_accounts_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('six_digit_code', models.IntegerField()),
                ('time', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Restore_Password',
        ),
    ]
