# Generated by Django 4.2.2 on 2023-08-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_verification_delete_restore_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=600)),
                ('phoneNumber', models.CharField(max_length=1200)),
                ('gmail_contact', models.CharField(max_length=1200)),
                ('message_contact', models.CharField(max_length=1000000)),
            ],
        ),
    ]
