# Generated by Django 4.2.3 on 2023-08-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_contactmessages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessages',
            old_name='gmail_contact',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contactmessages',
            old_name='message_contact',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='contactmessages',
            name='fullName',
        ),
        migrations.RemoveField(
            model_name='contactmessages',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='contactmessages',
            name='full_name',
            field=models.CharField(default='Anonim', max_length=100),
        ),
    ]
