# Generated by Django 4.2.3 on 2023-08-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_gmail_contact_contactmessages_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='tag',
        ),
        migrations.AddField(
            model_name='accounts',
            name='admin_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='olympian_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='teacher_tag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='trustable_tag',
            field=models.BooleanField(default=False),
        ),
    ]
