# Generated by Django 4.2.3 on 2023-08-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_accounts_tag_accounts_admin_tag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='trustable_tag',
            new_name='clever_tag',
        ),
    ]
