# Generated by Django 4.2.3 on 2023-08-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_trustable_tag_accounts_clever_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='solve_count',
            field=models.IntegerField(default=0),
        ),
    ]
