# Generated by Django 4.2.3 on 2023-08-23 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0020_alter_problems_user_added_and_more'),
        ('base', '0009_accounts_solve_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Account',
        ),
        migrations.RenameModel(
            old_name='ContactMessages',
            new_name='ContactMessage',
        ),
    ]
