# Generated by Django 4.2.3 on 2023-08-23 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_accounts_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='solve_count',
            new_name='point',
        ),
    ]
