# Generated by Django 4.2.2 on 2023-08-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_solve_count_account_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='theme',
            field=models.CharField(default='light', max_length=100),
        ),
    ]
