# Generated by Django 4.2.2 on 2023-08-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_account_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='theme',
        ),
    ]
