# Generated by Django 4.2.3 on 2023-08-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_account_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='real_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
