# Generated by Django 4.2.3 on 2023-08-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_account_real_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='real_name',
            field=models.CharField(max_length=100),
        ),
    ]
