# Generated by Django 4.2.3 on 2023-08-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_account_real_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='real_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
