# Generated by Django 4.2.3 on 2023-08-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_verification_real_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='real_name',
            field=models.CharField(max_length=100),
        ),
    ]
