# Generated by Django 4.2.3 on 2023-08-26 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_verification_real_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='real_name',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='verification',
            old_name='real_name',
            new_name='fullname',
        ),
    ]
