# Generated by Django 4.2.3 on 2023-08-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_real_name_account_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='fullname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='verification',
            name='fullname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
