# Generated by Django 4.2.3 on 2023-09-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_account_fullname_alter_verification_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='groups',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
