# Generated by Django 4.2.3 on 2023-09-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_account_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='groups',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
