# Generated by Django 4.2.3 on 2023-09-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_account_requests_alter_account_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='groups',
            field=models.CharField(default='%', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='account',
            name='requests',
            field=models.CharField(default='%', max_length=1000000),
        ),
    ]
