# Generated by Django 4.2.3 on 2023-10-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_account_groups_alter_account_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_photo',
            field=models.ImageField(default='profile_photos/default_pp.png', upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
