# Generated by Django 5.0 on 2023-12-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='notifications',
            field=models.CharField(default='%', max_length=1000000),
        ),
    ]
