# Generated by Django 5.0 on 2023-12-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_notfication'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notfication',
            new_name='Notification',
        ),
    ]
