# Generated by Django 5.0 on 2023-12-28 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_rename_notfication_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
