# Generated by Django 5.0 on 2024-01-05 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_notification_date_notification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='notifications',
        ),
    ]
