# Generated by Django 5.0 on 2024-01-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_remove_account_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='urls',
            field=models.CharField(default='%&', max_length=100000000000),
        ),
    ]
