# Generated by Django 5.0 on 2024-01-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_news_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
