# Generated by Django 5.0 on 2024-01-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_update'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Update',
            new_name='Version',
        ),
    ]
