# Generated by Django 4.2.3 on 2023-09-05 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_account_groups'),
        ('groups', '0002_alter_group_name_alter_group_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.account'),
        ),
        migrations.AddField(
            model_name='group',
            name='moderators',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='group',
            name='problems',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
