# Generated by Django 4.2.3 on 2023-09-05 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_account_groups'),
        ('groups', '0003_group_creator_group_moderators_group_problems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.account'),
        ),
    ]
