# Generated by Django 4.2.3 on 2023-09-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_group_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='participants',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
