# Generated by Django 4.2.2 on 2023-09-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_group_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='about',
            field=models.CharField(default=False, max_length=1000),
        ),
    ]
