# Generated by Django 4.2.2 on 2023-09-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_group_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='about',
            field=models.CharField(default='False', max_length=1000),
        ),
    ]
