# Generated by Django 4.2.2 on 2023-09-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_alter_group_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='participants',
            field=models.CharField(default='', max_length=100000000000000000000),
        ),
    ]
