# Generated by Django 4.2.2 on 2023-09-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_group_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='moderators',
        ),
        migrations.AddField(
            model_name='group',
            name='admins',
            field=models.CharField(default='', max_length=1000000000),
        ),
    ]
