# Generated by Django 4.2.3 on 2023-09-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_group_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='admins',
            field=models.CharField(default='%', max_length=1000000000),
        ),
        migrations.AlterField(
            model_name='group',
            name='participants',
            field=models.CharField(default='%', max_length=100000000000000000000),
        ),
        migrations.AlterField(
            model_name='group',
            name='problems',
            field=models.CharField(default='%', max_length=10000),
        ),
        migrations.AlterField(
            model_name='group',
            name='requests',
            field=models.CharField(default='%', max_length=100000000000000000000),
        ),
    ]
