# Generated by Django 4.2.3 on 2023-09-16 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_contest_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
    ]
