# Generated by Django 4.2.3 on 2023-09-16 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_alter_contest_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
