# Generated by Django 4.2.3 on 2023-09-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0016_group_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='problems',
            new_name='contests',
        ),
    ]
