# Generated by Django 4.2.3 on 2023-09-17 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0019_discussion_delete_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='group',
        ),
        migrations.AddField(
            model_name='discussion',
            name='contest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='groups.contest'),
            preserve_default=False,
        ),
    ]
