# Generated by Django 4.2.3 on 2023-10-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0020_remove_discussion_group_discussion_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='about',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
